server:
  port: 8086
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/detp}
    username: detp
    password: detp
management:
  endpoints:
    web:
      exposure:
        include: health
